AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM App
Globals:
  Function:
    Handler: index.handler
    Runtime: nodejs16.x
    Timeout: 180
    Architectures:
      - x86_64

Resources:
  HelloWorldApi:
    Type: AWS::Serverless::Api
    Properties:
      Description: Hello World REST API
      StageName: test

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/dist/hello-world
      Layers:
        - Ref: NpmLayer
        - Ref: LibsLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId:
              Ref: HelloWorldApi

  NpmLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: lambda_layers/npm-layer
      CompatibleArchitectures:
        - x86_64
      CompatibleRuntimes:
        - nodejs16.x
    Metadata:
      BuildMethod: nodejs16.x

  LibsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: lambda_layers/libs-layer
      CompatibleArchitectures:
        - x86_64
      CompatibleRuntimes:
        - nodejs16.x
    Metadata:
      BuildMethod: nodejs16.x

Outputs:
  HelloWorldApi:
    Value: !Sub "https://${HelloWorldApi}.execute-api.${AWS::Region}.amazonaws.com/test/hello"
  HelloWorldFunction:
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Value: !GetAtt HelloWorldFunctionRole.Arn
