AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM App
Globals:
  Function:
    Handler: index.handler
    Runtime: nodejs16.x
    Timeout: 180
    Architectures:
      - x86_64

Resources:
  HelloWorldApi:
    Type: AWS::Serverless::Api
    Properties:
      Description: Hello World REST API
      Name: hello-world-api
      StageName: test

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/hello-world/
      Events:
        HelloWorldApiEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: get
            RestApiId:
              Ref: HelloWorldApi
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        EntryPoints:
          - index.ts

Outputs:
  HelloWorldApi:
    Value: !Sub "https://${HelloWorldApi}.execute-api.${AWS::Region}.amazonaws.com/test/hello/"
  HelloWorldFunction:
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Value: !GetAtt HelloWorldFunctionRole.Arn
